[package]
name = "logspan"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
console-subscriber = "0.4.1"
tokio = { version = "1.47.1", features = ["full"] }
tokio-console = "0.1.13"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.20", features = ["json"] }

