[package]
name = "file_adapt"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.6"
tokio = { version = "1.48.0", features = ["full"] }
tokio-stream = { version = "0.1.17", features = ["io-util"] }
tokio-util = "0.7.16"
pin-project-lite = "0.2.16"
futures = "0.3.31"
