[package]
name = "shared_data"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { version = "1.3.3", features = ["i128"] }
crc32fast = "1.5.0"
serde = { version = "1.0.228", features = ["derive"] }
#serde_json = "1.0.145"
