[package]
name = "iterators"
version = "0.1.0"
edition = "2021"
authors = ["Rust学习者"]
description = "Rust 迭代器全面学习示例"
license = "MIT"
repository = "https://github.com/example/rust-iterators"

[dependencies]
